
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: front-end
spec:
  containers:
    - name: nginx-container
      image: nginx
---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:


apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:

---

