
---

# myapp-blue.yaml


apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-blue
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        version: v1
    spec:
      containers:
        - name: app-container
          image: myapp-image:1.0
  replicaset: 5
  selector:
    matchLabels:
      version: v1

---

# service-definition.yaml

apiVersion: v1
kind: Service
metadata:
  name: my-services
spec:
  selector:
    version: v1

---

#  Green deployment

---

# myapp-blue.yaml


apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-green
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        version: v2
    spec:
      containers:
        - name: app-container
          image: myapp-image:2.0
  replicaset: 5
  selector:
    matchLabels:
      version: v2

---

# service-definition.yaml

apiVersion: v1
kind: Service
metadata:
  name: my-services

spec:
  selector:
    version: v2

---


#=================================================================

# Canary Deployment


---

# myapp-primary.yaml


apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-primary
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        version: v1
        app: front-end
    spec:
      containers:
        - name: app-container
          image: myapp-image:1.0
  replicaset: 5
  selector:
    matchLabels:
      app: front-end



---

# service-definition.yaml

apiVersion: v1
kind: Service
metadata:
  name: my-services

spec:
  selector:
    app: front-end

---

#  Now move it to Canary deployment with initially 20% of the traffic with only 1 POD
#  in the replicaset



# myapp-primary.yaml


apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-canary
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        version: v2
        app: front-end
    spec:
      containers:
        - name: app-container
          image: myapp-image:2.0
  replicaset: 1
  selector:
    matchLabels:
      app: front-end



---

# service-definition.yaml

apiVersion: v1
kind: Service
metadata:
  name: my-services
spec:
  selector:
    app: front-end

---








